repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.9-for-vscode" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.1.2
          - "@prettier/plugin-xml@0.12.0"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.40.0" # Use the sha / tag you want to point at
    hooks:
      - id: eslint
